### ISSUE TITLE
Struttura StatePatern

### ISSUE THREAD

**Issue by AlbertoMartinezMontero** [AlbertoMartinezMontero/crud1-quattro#1]
-Interfaccia Sate
-Classe AutomaCrud
-Interfaccia Event
-Dichiarazione Classi eventi
-Struttura AutomaCrud
-Interfaccia GuiCrud
-Classe per Interfaccia utente JpForm

**Comment by francescofilitti** [comment]
8e1998decafcf155fcce952b5e2d6fb81c65fce5
